-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "standardCode" TEXT,
ADD COLUMN     "taxRate" DOUBLE PRECISION NOT NULL DEFAULT 19,
ADD COLUMN     "taxType" TEXT NOT NULL DEFAULT 'TAXED',
ADD COLUMN     "unitMeasure" TEXT NOT NULL DEFAULT '94';
